//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalInventory
    {
        public string SKU { get; set; }
        public string Status { get; set; }
        public string WorkStatus { get; set; }
        public string ProductName { get; set; }
        public string ProductFormat { get; set; }
        public int Quantity { get; set; }
        public bool WillShipInternationally { get; set; }
        public bool ExpeditedShipping { get; set; }
        public int ItemConditionCode { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> FullfilmentCenterId { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string ItemNoteDefault { get; set; }
        public Nullable<int> AmazonBestSellerRank { get; set; }
        public Nullable<bool> PullingComplete { get; set; }
        public int MerchantId { get; set; }
        public int TheSourceId { get; set; }
        public int BatchInputId { get; set; }
    }
}
