//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonModel.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewInventory
    {
        public int PurchaseId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string InventoryType { get; set; }
        public int QuantityPurchased { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string PurchaseReason { get; set; }
        public decimal PercentagePaid { get; set; }
        public string ItemId { get; set; }
        public Nullable<int> TheSourceId { get; set; }
    }
}
