//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonModel.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public int SalesId { get; set; }
        public string OrderId { get; set; }
        public string AltOrderId { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentsDate { get; set; }
        public Nullable<long> PaymentTransactionId { get; set; }
        public Nullable<decimal> OrderTotalPrice { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<long> BatchId { get; set; }
        public string BuyerEmail { get; set; }
        public string BuyerName { get; set; }
        public string ShippingMethod { get; set; }
        public string Status { get; set; }
        public string ShippingCarrier { get; set; }
        public string Tracking { get; set; }
        public string PaymentMethod { get; set; }
        public int MerchantId { get; set; }
        public int MarketplaceId { get; set; }
    }
}
