//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonModel.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderItemId { get; set; }
        public long OrderItemNumberId { get; set; }
        public string SKU { get; set; }
        public string CurrencyType { get; set; }
        public Nullable<System.DateTime> CurrencyConversionDate { get; set; }
        public Nullable<decimal> CurrencyConversionRate { get; set; }
        public string Location { get; set; }
        public string UPC { get; set; }
        public string ProductId { get; set; }
        public string ItemName { get; set; }
        public string ListingId { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> UnitTax { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> ShippingFeeTax { get; set; }
        public Nullable<int> QuantityPurchased { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> ItemFees { get; set; }
        public Nullable<int> ItemCondition { get; set; }
        public string ItemSource { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
    }
}
